### ISSUE TITLE
newline-delimited json

### ISSUE THREAD

**Issue by ngoldman** [maxogden/get-dat#2]
This may be the wrong place to ask, but I saw this line in [03-working-with-json.md](https://github.com/maxogden/get-dat/blob/15219f74f9b7d11ce6966611d9cb6ccacfca5bb0/03-working-with-json.md#write-some-json):

> There are three formats that dat can import: Newline-delimited JSON, CSV and Protocol Buffers. This file will cover JSON.

Does this mean dat doesn't support importing regular JSON (i.e. only newline-delimited JSON)?

**Comment by karissa** [comment]
ohh @chrisdickinson good idea. it might be nice to have that feature, but for now we'd probably recommend doing something like:

```
cat complex.json | parse-json '.rows > *' | dat import - -d complex
