### ISSUE TITLE
What's with picture-tube and a photo of Bob?

### ISSUE THREAD

**Issue by waldoj** [maxogden/get-dat#23]
I'm really confused by [the guidance about working with blobs](https://github.com/maxogden/get-dat/blob/master/markdown/04-working-with-files.md#adding-blobs-to-dat). Is there any reason to think that people would have `picture-tube` installed? Why even require it—can't we assume that if somebody double-clicks on an image, their OS will display it? What is the talk of a "server," why would somebody have a directory named `/pictures/` in the root of their drive, and how would a photo named `bob.png` get there?

Perhaps this whole portion of text was taken from some other document entirely, and dropped in here without any customizing?

**Comment by karissa** [comment]
Yeah, I'd say this isn't the best example. I'd actually like to use a city data example, since that easily spans use cases  in science, gov't, and journalism.
