### ISSUE TITLE
What is the "online get-dat web based environment"?

### ISSUE THREAD

**Issue by waldoj** [maxogden/get-dat#24]
From "[dat clone](https://github.com/maxogden/get-dat/blob/master/markdown/05-dat-clone.md#cloning-a-clone)":

> First, run dat listen --port=80 on the server. (You can skip this step if you aren't using our online get-dat web based environment)

_Am_ I using that? How would I know? At no point in this process was there a fork where people could choose to use "online get-dat web based environment" (or not), right?

I have no idea of how to reconcile this.

Also, this business of "the server" and using port 80 is entirely new. The prior steps have been on desktop machines. Are we assuming that people have access to a remote server that doesn't already have a web server listening on port 80? If I follow these instructions, we're telling somebody to do one thing on a remote server and something else on their local machine, which is a recipe for confusion.

**Comment by karissa** [comment]
I agree this was confusing, and I updated this language -- since they're in the web environment, they most certainly will be using the online get-dat web environment. Now it should be relatively more straightforward https://github.com/maxogden/get-dat/blob/master/markdown/05-dat-clone.md
