### ISSUE TITLE
Feedback on early version

### ISSUE THREAD

**Issue by richfitz** [maxogden/get-dat#4]
Against version b1976f91e8f4d9a66a7424dc19bcdbf83e86d377

# 1:

`dat init`

Missing: need to create new folder.  Something like `mkdir get-dat; cd get-dat`.

Should also say what is expected for empty (e.g. "There should be nothing in here (i.e., you should see only `.` and `..`)")

Is it worth giving hints about the name/description/publisher fields?  What they mean and which are required?

The final piece of information about missing files is kind of assumed by the rest of the commands on this page.

# 2:

This lesson seems out of order; the commands are presented without explanation and it's not clear what the expected outcome of the commands should be.  Also, because no concept of what is stored in `.dat` has been presented, the implications of deleting it are not clear.

From a practial view, deleting a dat repository is not going to be the first thing a user wants to do with it.

It's also confusing because the first time that `dat listen` is introduced as a command generates an error.  Because the user has no idea about what the command does, this seems cryptic.

There's also a potential trap here: if you run `dat init` in a repo that already has a listening `dat` running you get an unresponsive command:

```
dat init
dat listen
^z
dat init # hang
```

Also (sorry), the `dat listen` is an odd choice because it's the first dat-using command (after `init`) and yet it seems not to be necessary for the next set of dat-related things.  But introducing it first suggests to me at least that dat is something that needs to be run as a server the whole time, rather than something like git that mostly works just by having files in the right places.

# 3

Because the first set of data only has a single field in it, this is ambiguous.  From the example alone, this seems legit:

```
{"name": "alice",
 "age": "35"}
{"name":"bob",
 "age": "34"}
```

because it *seems* that what's important is that newlines separate entries.  Reading the last sentence though ("In newline-delimited JSON the only time you will see a line break (AKA newline) is between two objects") makes it clear: newlines are *only* allowed between entries.

> Make sure you are still in the same freshly initialized dat repository folder from the previous lessons.

For consistency with the previous lesson:

> Make sure `people.dat` existsin the same folder as the previous lesson by running `ls -a`.  You should see `. .. .dat dat.json people.json`

(as an aside, this is surprising:

```
~/tmp/get-dat » time dat import people.json --json
Elapsed      : 0 s
Parsed       : 28 B      (28 B/s)
 - changes : 2

Done
dat import people.json --json  0.86s user 0.11s system 100% cpu 0.959 total
```

...running dat import takes almost a second but reports 0s - it takes a noticable amount of time, so it's surprising to see `Elapsed: 0 s`.

On the second import of the `people.json` file using name as the key, I get 

```
~/tmp/get-dat » dat import people.json --json --primary=name
Elapsed      : 0 s
Parsed       : 28 B      (28 B/s)
 - changes : 2

Done
```

...the `changes : 2` line here is surprising if nothing is changed.

# 4:

The directories get confused here:

> We have conveniently provided a cat photo for you to use in this tutorial. It is called `cat.png` and should be in the `get-dat` directory.
>
> Running `ls` should list `cat.png`. If you don't see `cat.png` then make sure you have navigated into the `get-dat` directory in your terminal.

Except that contradicts the "start in an empty directory" requirement of the first lesson.  Presumably we're meant to copy the cat directory into the dat repo that we are creating, rather than the dat repo page.  Something like

```
curl -O https://raw.githubusercontent.com/maxogden/get-dat/master/cat.png
```

might avoid the difficulty of narrating copying things around all over the show, or alternatively start the lesson from within the cloned get-dat repo and then do

```
cp ../cat.png .
```

After `dat blobs put cat-pictures cat.png` it might be useful to do `dat cat` (as in the previous lesson).  If for no other reason than there is an obvious pun here.

In this lesson, "directory" is used, elsewhere "folder" is used (folder is also used here).

**Comment by karissa** [comment]
I think this is safely closed, because we've changed a bunch and this was based on the alpha version of dat.

@richfitz , if you have time, can you check out the new version of get-dat?

maxogden.github.io/get-dat/
